# Generated by Django 4.1.4 on 2022-12-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='mail',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
    ]
