# Generated by Django 4.1.4 on 2022-12-27 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.job')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
        ),
    ]
