# Generated by Django 4.1.4 on 2022-12-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidatejobmap_candidate_delete_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatejobmap',
            name='job_owner',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
