# Generated by Django 4.1.4 on 2022-12-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidatejobmap_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatejobmap',
            name='job_owner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
